version: "3.5"
services:
  # Data store
  first-app-mysql:
    image: mysql:latest
    container_name: first-app-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: db
      MYSQL_USER: docker
      MYSQL_PASSWORD: mysql
      TZ: 'Asia/Tokyo'
    ports:
      - "3306:3306"

networks:
  network0: